### ISSUE TITLE
GDI object leak

### ISSUE THREAD

**Issue by luca-vari** [Virtual-TreeView/RibbonFramework#108]
Hi,
The current version of the ribbon framework leaks Windows GDI objects. You can monitor GDI object usage in the Windows Task Manager (e.g. see [here](https://superuser.com/questions/1206351/where-in-task-manager-can-i-find-information-about-gdi-objects-or-handles-per-pr)).

I can reproduce the issue on Windows 10 using the Ribbon Designer WordPad template:

1. Launch the Ribbon Designer.
1. Select _File>New_ menu option. The _New Ribbon Document_ dialog will display.
1. Select the _Create a new Ribbon document using the WordPand template_ radio button.
1. Enter a directory in the _Save the document in the following directory_ edit box.
1. Select the _OK_ button.
1. Select the _Project>Preview_ menu option. The _Ribbon Preview_ will display.
1. Note the number of GDI objects reported in the Task Manager for the _RibbonDesigner.exe_ application.
1. Close the _Ribbon Preview_.
1. Repeat as many times as you like from step 6.

You will note that the number of GDI objects used consistently increases but it should remain roughly the same on each execution of the _Ribbon Preview_. When the GDI object usage hits the application limit (10,000) the Ribbon Designer will crash.

The reason that that this is happening is that the [IUIFramework::Destroy](https://docs.microsoft.com/en-us/windows/win32/api/uiribbon/nf-uiribbon-iuiframework-destroy) method is never called from the _TUIRibbon_ class. It looks like it was called in previous versions of the framework but removed in commits df9da3a and 75dfaab.

For df9da3a it possible these lines were inadvertently removed:
```
if Assigned(FFramework) then
    FFramework.Destroy;
```
For 75dfaab may be the change introduced in df9da3a was copied...?

Note that the `TUIRibbon.DestroyWnd` procedure is not called as a consequence of the `TUIRibbon.Destroy` destructor being called so that a call to `IUIFramework::Destroy` would be required in both code paths. This was surprising to me; it is a consequence of the `TWinControl.WMNCDestroy` procedure (the handler for the `WM_NCDESTROY` windows message) clearing the windows handle of the ribbon *before* `TUIRibbon.Destroy` is called. The `TUIRibbon.DestroyWnd` procedure doesn't get called if the control doesn't have a handle...

Cheers,
Luca

**Comment by SaschaSchaefer** [comment]
Added call to IUIFramework::Destroy again.

It was removed because it caused occasional AVs. I did not notice the leaks since I never used the Ribbon in an application that creates a ribbon multiple times.

The AVs could be solved by calling IUIFramework::Destroy **before** freeing the commands. I'm still not sure why this is necessary though.

**Comment by luca-vari** [comment]
Thank you!
