### ISSUE TITLE
Change customize qat button icon 

### ISSUE THREAD

**Issue by Radu13** [Virtual-TreeView/RibbonFramework#113]
How to edit the icon of the "customize qat" button?
Image below:
![image](https://user-images.githubusercontent.com/25487544/68996502-50fe0800-089b-11ea-9d8b-acd1024c6a07.png)

**Comment by joachimmarder** [comment]
I don't think those images can be changed or customized at all, they are most likely a fix part of the Windows Ribbon Framework.

**Comment by Radu13** [comment]
Every windows icons are stored somewhere, so it should be possible, especially knowing how you load them for a custom qat

**Comment by Radu13** [comment]
> 
> 
> I don't think those images can be changed or customized at all, they are most likely a fix part of the Windows Ribbon Framework.

Every windows icons are stored somewhere, so it should be possible, especially knowing how you load them for a custom qat

**Comment by joachimmarder** [comment]
Yes, of course the icon will be part of some Windows DLL, and of course the icon can be changed using a resource editor, destroying its digital signature. But that will never become a feature of this component.

**Comment by Radu13** [comment]
I know it's a thing outside this component but maybe you know in which dll this icon is actually stored in after you create a custom ribbon with this software.
