### ISSUE TITLE
Colorization problematic

### ISSUE THREAD

**Issue by markwilliams1234** [Virtual-TreeView/RibbonFramework#114]
I have an app for which I change the colors of the ribbon to match whichever form style is selected.

The background is meant to be dark for dark styles with a light font. When I opened the app a few weeks ago this seemed to work fine.

I opened it yesterday and the ribbon background color now shows as light with dark styles.  Nothing I do can get it to set it as dark. I have installed the latest version of RibbonFramework to see if that makes any difference. It doesn't.

I have tested it in ribbon designer. For example, Hue: 160, Sat: 0, Brightness: 36 should produce a dark slate background. It is now producing a very light green color.

As I have only recently updated RibbonFramework,, it would seem the problem cannot be to do with changes to that. Is there some issue with Windows itself and a recent Windows Update?

**Comment by joachimmarder** [comment]
Which Windows version are you using? 

As far as I know colorizing the ribbon background is no longer supported on Windows 10, but recent versions do have a dark mode for the ribbon, for which we added support in V2.7.

**Comment by markwilliams1234** [comment]
Windows 10 Version 1903. I'll try the latest ribbonFramework and see where that gets me. Thanks

**Comment by markwilliams1234** [comment]
I am using the latest version. I just didn't know it. I can see DarkMode and how it works. Presumably, darkmode will only work for windows versions above a certain number. Do you know what version no that is?

**Comment by markwilliams1234** [comment]
Would it be possible to have an emulate DarkMode function in the Ribbon Framework for Windows versions that don't support it natively?

**Comment by joachimmarder** [comment]
> Do you know what version no that is?

Windows 10 1809

> Would it be possible to have an emulate DarkMode function in the Ribbon Framework for Windows versions that don't support it natively?

No.
