### ISSUE TITLE
ImageList of ActionsManager is not considered when ImageList is located in a form other than main form.

### ISSUE THREAD

**Issue by joerg-github** [Virtual-TreeView/RibbonFramework#116]
If the properties for "Images" or "LargeImages" point to a list, which are located e.g. in a data module, 

    LargeImages = dmImages.imlMainLarge 
    Images = dmImages.imlMain

and the data module is created via the project source

    ...
    Application.CreateForm(TfrmMain, frmMain);
    Application.CreateForm(TdmImages, dmImages);
    ...

the properties are nil at the time TUIRibbon.RegisterForImageChanges is called.

I first helped myself by making the method RegisterForImageChanges public and adding the call "ImageListChange(nil)" to it. On the OnShow event of the main form I called RegisterForImageChanges.

Did I miss something or how should this be solved normally?

**Comment by joachimmarder** [comment]
Hmm, not sure what the call sequence is in this scenario, if. e.g. CreateWnd() is called before the data module is created. Can you supply a small sample project?

**Comment by joerg-github** [comment]
While preparing a sample project I discovered that the sequence can be different.

At the program where I noticed the problem, I was about to switch it from the TRibbon component of the Vcl.Ribbon unit to the RibbonFramework. At that time I had the problem the VCL component was still on the form to compare. But this component seems to cause a different call sequence.

Call stack when VCL Ribbon is on the form:

	UIRibbon.TUIRibbon.RegisterForImageChanges
	UIRibbon.TUIRibbon.Load
	UIRibbon.TUIRibbon.CreateWnd
	Vcl.Controls.TWinControl.CreateHandle
	Vcl.Controls.TWinControl.HandleNeeded
	Vcl.Controls.TWinControl.GetHandle
	Vcl.Controls.TWinControl.GetClientRect
	Vcl.Forms.DoUpdateControls($99F1F60)
	Vcl.Forms.TCustomForm.UpdateGlassFrameControls((1375472, 0, 18, 0, (1375472, 0), (18, 0)))
	Vcl.Forms.TCustomForm.AlignControls(???,???)
	Vcl.Controls.TWinControl.AlignControl(nil)
	Vcl.Controls.TWinControl.Realign
	Vcl.Controls.TWinControl.EnableAlign
	Vcl.Forms.TCustomForm.Create($5A64970)
	Vcl.Forms.TApplication.CreateForm(TComponentClass($140F6F8),(no value))

Call stack when it is not on the form:

	UIRibbon.TUIRibbon.RegisterForImageChanges
	UIRibbon.TUIRibbon.Load
	UIRibbon.TUIRibbon.CreateWnd
	Vcl.Controls.TWinControl.CreateHandle
	Vcl.Controls.TWinControl.UpdateShowing
	Vcl.Controls.TWinControl.UpdateShowing
	Vcl.Controls.TWinControl.UpdateControlState
	Vcl.Controls.TWinControl.CMVisibleChanged(???)
	System.TObject.Dispatch((no value))
	Vcl.Controls.TControl.WndProc($14FE00)
	Vcl.Controls.TWinControl.WndProc($14FE00)
	Vcl.Forms.TCustomForm.WndProc($14FE00)
	Vcl.Controls.TControl.Perform(???,???,???)
	Vcl.Controls.TControl.SetVisible(True)
	Vcl.Forms.TCustomForm.SetVisible(True)
	Vcl.Forms.TApplication.Run

So one can see that with the VCL Ribbon the CreateForm already causes a CreateWnd, but without it behaves like expected.

I don't know if there might be other components that have an impact on the creation sequence and therefore an adaptation of the framework is helpful.

For me it is ok for now and the ticket can be closed from my point of view.
